version: '3.9'

services:
  spring-boot:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_AUTHOR: ${APP_AUTHOR}
  nginx:
    build: ./nginx
    depends_on:
      - spring-boot
    ports:
      - "80:80"